Pause native build

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -45,52 +45,52 @@ jobs:
         curl --fail --show-error --silent http://localhost:8080
         curl --fail --show-error --silent http://localhost:8080/entries/412
         pkill -KILL java
-    - name: Native Image
-      if: github.ref == 'refs/heads/main'
-      run: |
-        set -e
-        ./mvnw -V --no-transfer-progress -Pnative native:compile -DskipTests
-        ./target/blog-frontend --management.otlp.tracing.endpoint=https://httpbin.org/post &
-        .github/workflows/wait.sh
-        curl --fail --show-error --silent http://localhost:8080
-        curl --fail --show-error --silent http://localhost:8080/entries/412
-        pkill -KILL blog-frontend || true
-    - name: Import Secrets
-      if: github.ref == 'refs/heads/main'
-      id: secrets
-      uses: hashicorp/vault-action@v3.0.0
-      with:
-        exportToken: true
-        exportEnv: true
-        method: jwt
-        url: ${{ secrets.VAULT_ADDR }}
-        role: cicd
-        secrets: |
-          kv/data/cicd/github api_token | GITHUB_API_TOKEN ;
-    - name: Docker Login
-      if: github.ref == 'refs/heads/main'
-      run: docker login ghcr.io -u ${GITHUB_REPOSITORY_OWNER} -p ${GITHUB_API_TOKEN}
-    - name: Install Pack
-      if: github.ref == 'refs/heads/main'
-      uses: buildpacks/github-actions/setup-pack@v5.6.0
-    - name: Pack Build
-      if: github.ref == 'refs/heads/main'
-      run: |
-        mkdir -p pack
-        mv ./target/blog-frontend ./pack
-        cat <<EOF > pack/Procfile
-        web: ./blog-frontend
-        EOF
-        pack build ghcr.io/${GITHUB_REPOSITORY_OWNER}/blog-frontend \
-          --env BP_OCI_SOURCE=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA} \
-          --env BP_OCI_REVISION=${GITHUB_REF_NAME}@sha1:${GITHUB_SHA} \
-          --gid 1000 \
-          --publish \
-          --builder paketobuildpacks/builder-jammy-tiny \
-          --buildpack gcr.io/paketo-buildpacks/image-labels \
-          --buildpack gcr.io/paketo-buildpacks/procfile \
-          --path pack
-    - name: Revoke token
-      if: always()
-      run: |
-        curl -X POST -s -H "X-Vault-Token: ${VAULT_TOKEN}" ${{ secrets.VAULT_ADDR }}/v1/auth/token/revoke-self || true
+#    - name: Native Image
+#      if: github.ref == 'refs/heads/main'
+#      run: |
+#        set -e
+#        ./mvnw -V --no-transfer-progress -Pnative native:compile -DskipTests
+#        ./target/blog-frontend --management.otlp.tracing.endpoint=https://httpbin.org/post &
+#        .github/workflows/wait.sh
+#        curl --fail --show-error --silent http://localhost:8080
+#        curl --fail --show-error --silent http://localhost:8080/entries/412
+#        pkill -KILL blog-frontend || true
+#    - name: Import Secrets
+#      if: github.ref == 'refs/heads/main'
+#      id: secrets
+#      uses: hashicorp/vault-action@v3.0.0
+#      with:
+#        exportToken: true
+#        exportEnv: true
+#        method: jwt
+#        url: ${{ secrets.VAULT_ADDR }}
+#        role: cicd
+#        secrets: |
+#          kv/data/cicd/github api_token | GITHUB_API_TOKEN ;
+#    - name: Docker Login
+#      if: github.ref == 'refs/heads/main'
+#      run: docker login ghcr.io -u ${GITHUB_REPOSITORY_OWNER} -p ${GITHUB_API_TOKEN}
+#    - name: Install Pack
+#      if: github.ref == 'refs/heads/main'
+#      uses: buildpacks/github-actions/setup-pack@v5.6.0
+#    - name: Pack Build
+#      if: github.ref == 'refs/heads/main'
+#      run: |
+#        mkdir -p pack
+#        mv ./target/blog-frontend ./pack
+#        cat <<EOF > pack/Procfile
+#        web: ./blog-frontend
+#        EOF
+#        pack build ghcr.io/${GITHUB_REPOSITORY_OWNER}/blog-frontend \
+#          --env BP_OCI_SOURCE=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA} \
+#          --env BP_OCI_REVISION=${GITHUB_REF_NAME}@sha1:${GITHUB_SHA} \
+#          --gid 1000 \
+#          --publish \
+#          --builder paketobuildpacks/builder-jammy-tiny \
+#          --buildpack gcr.io/paketo-buildpacks/image-labels \
+#          --buildpack gcr.io/paketo-buildpacks/procfile \
+#          --path pack
+#    - name: Revoke token
+#      if: always()
+#      run: |
+#        curl -X POST -s -H "X-Vault-Token: ${VAULT_TOKEN}" ${{ secrets.VAULT_ADDR }}/v1/auth/token/revoke-self || true
